---
functional:
  - Пользователь должен иметь возможность авторизоваться, в том числе через gitHub или Discord
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность создать игру с различными модификаторами
  - Пользователь должен иметь возможность подключиться к уже созданной игре
  - Пользователь должен иметь возможность присоединиться к игре
  - На сайте должна быть реализована возможность проиграть
  - На сайте должна быть реализована возможность одержать победу
  - На сайте должен быть реализован чат
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - На сайте должна быть реализована возможность проверки правильности кода, посредством встроенного компилятора
  - На сайте должна быть реализована возможность просмотра статистики игрока
  - На сайте должна быть реализована возможность редактирования профиля
  - На сайте должна быть реализована система рейтинга игроков
  - На сайте должна быть реализована возможность сыграть реванш
  - На сайте, в редакторе кода должна быть реализована возможность смены темы
  - На сайте должна быть реализована возможность сортировки игр по тегам и уровню сложности
  - На сайте должна быть реализована возможность сдачи
  - На сайте должна быть реализована возможность просмотра истории игр
  - На сайте должна быть реализована возможность просмотра истории турниров
  - На сайте должна быть реализована возможность отправки приватных сообщений игрокам в сети
  - На сайте должна быть реализована возможность смены языка, на котором представлена задача
  - На сайте должна быть реализована возможность смены языка программирования
