---
functional:
  - Пользователь должен иметь возможность авторизоваться, в том числе через gitHub или Discord
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность подключиться к уже созданной игре
  - Пользователь должен иметь возможность пригласить другого пользователя в игру
  - Пользователь должен иметь возможность присоедениться к игре по приглашению
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - На сайте должна быть реализована возможность проверки правильности кода, посредством встроенного компилятора
  - На сайте должна быть реализована возможность выбирать модификаторы игры при ее создании
  - Пользователь должен иметь возможность присоединиться к публичной игре с главной формы сайта
